### ISSUE TITLE
Windows installation issues; atactk patches installation; bowtie2 index [solved]

### ISSUE THREAD

**Issue by jingnie0512** [fl-yu/CUT-RUNTools-2.0#1] opened 2021-02-02 17:58 UTC
Hi, I'm a biologist with no data science background. I was trying to analyze my own CUT&RUN data, but have difficulty installing the CUT&RUNTools 2.0 pipeline. I followed the installation guide and installed Python, R, Java, Perl, GCC, and Anaconda, and tried to run the installation codes in Powershell Prompt from Anaconda (Windows 10). But whenever I run the codes which start with "source" (e.g. source atactk.install.sh), I get an error message like this:

(cutruntools2.1) PS C:\Users\jingnie> source atactk.install.sh
source : The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ source atactk.install.sh
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (source:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by fl-yu** [comment] 2021-02-02 19:17
Hi, thank you for your interest in our work.
I am sorry that it does not support the Windows system, could you try a UNIX system environment like Mac or Linux?

**Comment by jingnie0512** [comment] 2021-02-02 21:28
Thank you very much for your answer! I'll try installing Linux and then try to install CUT&RUNTools 2.0. Congratulations on your BioRxiv paper!

**Comment by fl-yu** [comment] 2021-02-02 22:37
Thank you! Let me know if you run into any issue.

**Comment by KQ2012** [comment] 2021-02-07 01:45
Hi, I have the installing problem as well. Please advise. Thanks!

1st error when running source atactk.install.sh 

"Successfully installed atactk-0.1.6
patching file make_cut_matrix
atactk.install.sh:cd:21: no such file or directory: /Users/kunhuaqin/.local/lib/python2.7/site-packages/atactk"

solution tried: changed the "~/.local/lib/python2.7/site-packages/atactk" in the atactk install script to "python3.6"

Error 2:

Successfully installed atactk-0.1.6
patching file make_cut_matrix
patch unexpectedly ends in middle of line
patching file metrics.py
patch unexpectedly ends in middle of line
Hunk #3 succeeded at 239 with fuzz 1.

**Comment by fl-yu** [comment] 2021-02-07 03:23
Thank you for your feedback.
This information indicates that the patches already applied and committed to the repository which has thus no reason to be reapplied. So you can ignore this and go-ahead.

**Comment by KQ2012** [comment] 2021-02-07 04:04
Thanks so much for your reply! 
 
The problem is when running the validation script, it still shows the following:

./validate.py ../bulk-config.json --ignore-input-output --software

make_cut_matrix is not found in ~/.local/bin/

But I check this dir from my computer, I actually saw the make_cut_matrix and make_cut_matrix.patch as well.
So I originally thought this is because the package failed to install correctly.

Thanks!

**Comment by fl-yu** [comment] 2021-02-07 15:13
Hi, KQ2012. It is the first time to see this.
As per your description, the make_cut_matrix file physically exists. Could you test the command  `~/.local/bin/make_cut_matrix` to see if this could work properly? If yes, I think it should be fine to use it in the pipeline. I think the problem may be the check function used in the validation.py can not identify make_cut_matrix file. 
One simple solution is to comment on the checking command of make_cut_matrix in the validation.py (add `#` in front of the lines 99 and 100 in the validation.py)
>  On some platforms, this function may return False if permission is not granted to execute os.stat() on the requested file, even if the path physically exists met this

**Comment by KQ2012** [comment] 2021-02-07 22:24
Thanks again for your super fast reply!

Yes, I tried what you suggested and the this seems functional: 
$ ~/.local/bin/make_cut_matrix
usage: make_cut_matrix [-h] (-a | -d) -b BINS [-F EXCLUDE_FLAGS]
                       [-f INCLUDE_FLAGS] [-o CUT_POINT_OFFSET] [-p PARALLEL]
                       [-q QUALITY] [-r EXTENSION] [-v] [--version]
                       BAM-file-of-aligned-reads BED-file-of-motifs
make_cut_matrix: error: the following arguments are required: -b/--bins, BAM-file-of-aligned-reads, BED-file-of-motifs

It might be something I installed previously causing this.

I did a test run using the data in the example folder, the timing went very well, but there seems something wrong with the bowtie2. This is what the log shows: 

(ERR): "/Volumes/Backup/CUT-RUNTools-2.0-master/index/hg19/Bowtie2Index/genome" does not exist or is not a Bowtie 2 index
Exiting now ...

the bowtie2 index I specified in the config file is ""/Volumes/Backup/CUT-RUNTools-2.0-master/index/hg19/Bowtie2Index/"
Any idea what causing this? I appreciate your help.

**Comment by fl-yu** [comment] 2021-02-08 01:15
Great to hear it works well!
That may be the case.

> It might be something I installed previously causing this.

According to your setting, you should probably make sure that the bowtie2 index files are named consistently as something like `genome.1.bt2` and `genome.2.bt2` etc in this folder /Volumes/Backup/CUT-RUNTools-2.0-master/index/hg19/Bowtie2Index.

Hoping you will enjoy our tool, I will close this issue and please let me know (and other potential users) by creating another issue if you run into other issues.

**Comment by fl-yu** [comment] 2021-02-08 01:20
reopen

**Closed** 2021-07-01 12:32 UTC
