### ISSUE TITLE
empty trim2 directory

### ISSUE THREAD

**Issue by Yuling-Zhao** [fl-yu/CUT-RUNTools-2.0#48] opened 2022-06-09 13:11 UTC
Dear Fulong,

Sorry for bothering again. Now I have the right adaptor sequence fasta and added it to the programme. However, the logs seem to tell only first trimming happened. I got perl warning:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = (unset),
    LC_ALL = (unset),
    LC_CTYPE = "UTF-8",
    LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").

I tried to fix it by adding the following to ~/.bashrc
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

After source ~/.bashrc, the waring from perl disappeared but still nothing coming up in trim2 directory. Therefore, no input to continue the analysis. There was also error for no version finding of bowtie2.

Our bioinformatic facility is also helping to solve this problem. But I think maybe you more about this issue.

Thanks for your help in advance!

Best,
Yuling

**Comment by fl-yu** [comment] 2022-06-10 01:44
Hi Yuling it seems that the issue is about the setting of software based on your description. Any luck to fix them? Will you be able to invoke kseq by `$kseqbin/kseq_test`?

**Comment by fl-yu** [comment] 2022-06-10 03:01
Great! The software setting is very tricky sometimes. I suggest that you may adapt the pipeline a bit to just use reads trimmed from step1 for alignment if it is difficult to fix that issue as the second step trim is actually helpful but slightly on alignment. Please let me know if have difficulty with this.

**Comment by fl-yu** [comment] 2022-07-04 01:10
I will close this thread but please feel free to reopen it if you have questions.

**Closed by fl-yu** 2022-07-04 01:10 UTC

**Comment by sunta3iouxos** [comment] 2023-07-04 14:53
hi there I got the same issue, I did some debugging and found that the read.lenght is not defined:
in the bulk_pipeline.sh:
```
echo "$kseqbin/kseq_test $trimdir/"$base"_1.paired.fastq.gz $len $trimdir2/"$base"_1.paired.fastq.gz" > $logdir/${base}_kseq_test_1.log
echo "$kseqbin/kseq_test $trimdir/"$base"_2.paired.fastq.gz $len $trimdir2/"$base"_2.paired.fastq.gz" > $logdir/${base}_kseq_test_2.log
$kseqbin/kseq_test $trimdir/"$base"_1.paired.fastq.gz $len $trimdir2/"$base"_1.paired.fastq.gz >> $logdir/${base}_kseq_test_1.log 2>&1
$kseqbin/kseq_test $trimdir/"$base"_2.paired.fastq.gz $len $trimdir2/"$base"_2.paired.fastq.gz >> $logdir/${base}_kseq_test_2.log 2>&1
```
the echo and the  >> is to get the error:

> /home/user/CUT-RUNTools-2.0/install/kseq_test /home/user/bulk-example-test/GATA1_D7_30min_chr11/trimmed/GATA1_D7_30min_chr11_1.paired.fastq.gz  /home/user/bulk-example-test/GATA1_D7_30min_chr11/trimmed2/GATA1_D7_30min_chr11_1.paired.fastq.gz
> Usage: /home/user/CUT-RUNTools-2.0/install/kseq_test <in.seq> <read.length> <outfile>

shouldnt there be a condition for the existence or not of the ```<read.length>```? 
So, how do we define the read.lenght and where? how is this relative to the cut&run or Cut&tag?
Should we just remove this step?
